/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_lab_jesusr;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Random;
import static proyecto_lab_jesusr.Experimento_Matrices.random;
public class Menu_Matematico extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Matematico
     */
    public Menu_Matematico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Multiplicacion de Matrices");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Conversiones");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(102, 0, 0));
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Recursion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addGap(145, 145, 145))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(43, 43, 43)
                .addComponent(jButton3)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         new Menu_Coversion().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new Menu1().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int ColsA=0;
        int filasB=0;
        int filasA = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese numero de filas de matriz A: "));
        
        do {
            ColsA = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese numero de columnas de matriz A: "));
            
            filasB = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese numero de filas de matriz B: "));
            

            if (filasB != ColsA) {
                JOptionPane.showInternalMessageDialog(null,"Las columnas de A ocupan ser igual a las filas de B, intente de nuevo.");
            }
        } while (filasB != ColsA);
       int ColsB=Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese numero de columnas de matriz B: "));
       
        int[][] A = new int[filasA][ColsA];
        int[][] B = new int[filasB][ColsB];
        int[][] C = new int[A.length][B[0].length];
        matriz(0, 0, A);
        matriz(0, 0, B);
         
        Mult(A, B, C, 0, 0);
        JOptionPane.showInternalMessageDialog(null,jamon(0, 0, A)+"\n"+jamon(0, 0, B)+"\n ="+jamon(0, 0, C));
        
     
         
         
    }//GEN-LAST:event_jButton1ActionPerformed
/*Llenado*/public static int [][] matriz (int i, int j, int [][]Mat1){
    if (i == Mat1.length-1 && j == Mat1[0].length-1) {
        Mat1[i][j] = random.nextInt(9);
    }
    else if(j < Mat1[0].length-1){
         Mat1[i][j] = random.nextInt(9);
         matriz(i, ++j, Mat1);
    } else if(j == Mat1[0].length-1){
         Mat1[i][j] = random.nextInt(9);
         matriz(++i, 0, Mat1);
    }
    return Mat1;
}

/*Imprimir*/public static String jamon (int i, int j, int [][]Mat1){
    if (i == Mat1.length-1 && j == Mat1[0].length-1) {
        return("[" + Mat1[i][j] + "]\n"); 
    }
    else if(j < Mat1[0].length-1){
           return("[" + Mat1[i][j] + "]"  )+jamon(i, ++j, Mat1);
            
    } else if(j == Mat1[0].length-1){
         return("[" + Mat1[i][j] + "]\n" )+jamon(++i, 0, Mat1);
            
         
    }
   return " ";
}

/*Rowproduct*/public static int rowproduct (int[][]A, int [][]B, int i, int j, int k){
    if(k< A[0].length-1){
        return (A[i][k]* B[k][j]) + rowproduct(A,B,i, j, ++k);
    }else{
        return (A[i][k]* B[k][j]);
    }
        
    
    
}
//Para el row product agarra 2 matrices y lo que hace es agarrar la fila i de A y la columna j de B
// El valor de k puede ser A[0].lenght o  B.length
//El valor de k va a ir cambiando los elementos que se multiplican segun las reglas de multiplicacion de matrices
// La funcion devuelve la multiplicacion individual de cada 2 elementos y las va sumando hasta salir de la funcion
//lo cual da el elemento [i][j] del producto de matriz A y B.
 
public static int[][] Mult (int[][]A, int [][]B, int [][]C, int i, int j){
    if(i== A.length-1 && j== B[0].length-1){
        C[i][j]= rowproduct(A,B,i,j, 0);
    }else if(j<B[0].length-1 ){
         C[i][j]= rowproduct(A,B,i,j, 0);
         Mult(A,B,C, i, ++j);
    }else if(j== B[0].length-1){
        C[i][j]= rowproduct(A,B,i,j, 0);
         Mult(A,B,C, ++i, 0);
    }
    return C;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Matematico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Matematico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Matematico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Matematico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Matematico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
